# @package _group_
_target_: mbrl.models.GaussianMLP
device: ${device}
num_layers: 4
in_size: ???
out_size: ???
ensemble_size: 7
hid_size: 200
deterministic: true
propagation_method: random_model
activation_fn_cfg:
  _target_: torch.nn.SiLU
