# @package _group_

_target_: mbrl.planning.BCCEMOptimizer
num_iterations: ${overrides.cem_num_iters}
elite_ratio: ${overrides.cem_elite_ratio}
population_size: ${overrides.cem_population_size_per_worker}
total_population_size: ${overrides.cem_population_size}
alpha: ${overrides.cem_alpha}
num_workers: ${overrides.cem_num_workers}
lower_bound: ???
upper_bound: ???
return_mean_elites: true
device: ${device}
clipped_normal: ${overrides.cem_clipped_normal}
init_jitter_scale: ${overrides.cem_init_jitter_scale}

# ---- BC-CEM knobs ----
# Consensus pull strength.
consensus_coef: ${overrides.cem_consensus_coef}
consensus_anneal_power: ${overrides.cem_consensus_anneal_power}

# Worker weighting for centroid / IR.
use_value_weights: ${overrides.cem_use_value_weights}

# IR gating thresholds
ir_low: ${overrides.cem_ir_low}
ir_high: ${overrides.cem_ir_high}

# Early stopping.
early_stop: ${overrides.cem_early_stop}
early_stop_mu: ${overrides.cem_early_stop_mu}
early_stop_patience: ${overrides.cem_early_stop_patience}
