# @package _group_

_target_: mbrl.planning.BCCEMOptimizer
num_iterations: ${overrides.cem_num_iters}
elite_ratio: ${overrides.cem_elite_ratio}
population_size: ${overrides.cem_population_size_per_worker}
total_population_size: ${overrides.bccem_total_population_size:null}
alpha: ${overrides.cem_alpha}
num_workers: ${overrides.cem_num_workers}
lower_bound: ???
upper_bound: ???
return_mean_elites: true
device: ${device}
clipped_normal: ${overrides.cem_clipped_normal}
init_jitter_scale: ${overrides.cem_init_jitter_scale}

# BC / IR knobs
tau: ${overrides.bccem_tau:1.0}
enable_precond: ${overrides.bccem_enable_precond:false}
beta2: ${overrides.bccem_beta2:0.9}
ir_low: ${overrides.bccem_ir_low:0.25}
ir_high: ${overrides.bccem_ir_high:1.5}
precond_min: ${overrides.bccem_precond_min:0.2}
precond_max: ${overrides.bccem_precond_max:1.0}

# Early stopping
early_stop: ${overrides.bccem_early_stop:false}
min_iterations: ${overrides.bccem_min_iterations:2}
patience: ${overrides.bccem_patience:1}
improvement_tol: ${overrides.bccem_improvement_tol:1e-3}
stop_ir: ${overrides.bccem_stop_ir:0.1}

# Persistence
persist_state: ${overrides.bccem_persist_state:true}
anchor_x0: ${overrides.bccem_anchor_x0:0.0}

# Injection / respawn
inject_mean: ${overrides.bccem_inject_mean:true}
inject_centroid: ${overrides.bccem_inject_centroid:true}
respawn_weight_thresh: ${overrides.bccem_respawn_weight_thresh:0.0}
respawn_delta: ${overrides.bccem_respawn_delta:0.5}
