# @package _group_

_target_: mbrl.planning.BCCEMOptimizer
num_iterations: ${overrides.cem_num_iters}
elite_ratio: ${overrides.cem_elite_ratio}
population_size: ${overrides.cem_population_size_per_worker}
total_population_size: ${overrides.cem_population_size}
alpha: ${overrides.cem_alpha}
num_workers: ${overrides.cem_num_workers}
lower_bound: ???
upper_bound: ???
return_mean_elites: true
device: ${device}
clipped_normal: ${overrides.cem_clipped_normal}
init_jitter_scale: ${overrides.cem_init_jitter_scale}

# ---- BC-CEM knobs ----
# Consensus pull strength.
consensus_coef: 0.25
consensus_anneal_power: 0.75

# Worker weighting for centroid / IR.
use_value_weights: true

# IR gating thresholds
ir_low: 0.3
ir_high: 0.5
ir_high_target: 0.8
ir_ema_alpha: 0.1

# Early stopping.
early_stop: true
early_stop_ir: 0.2
early_stop_mu: 1e-2
early_stop_patience: 1
