# @package _group_

_target_: mbrl.planning.DecentCEMOptimizer
num_iterations: ${overrides.cem_num_iters}
elite_ratio: ${overrides.cem_elite_ratio}
population_size: ${overrides.cem_population_size_per_worker}
total_population_size: ${overrides.cem_population_size}
alpha: ${overrides.cem_alpha}
num_workers: ${overrides.cem_num_workers}
lower_bound: ???
upper_bound: ???
return_mean_elites: true
device: ${device}
clipped_normal: ${overrides.cem_clipped_normal}
init_jitter_scale: ${overrides.cem_init_jitter_scale}
