# @package _group_

_target_: mbrl.planning.GMMCEMOptimizer
num_iterations: ${overrides.cem_num_iters}
elite_ratio: ${overrides.cem_elite_ratio}
population_size: ${oc.select:overrides.cem_population_size_per_worker,${overrides.cem_population_size}}
alpha: ${overrides.cem_alpha}
num_workers: ${oc.select:overrides.cem_num_workers,4}
lower_bound: ???
upper_bound: ???
return_mean_elites: true
device: ${device}
clipped_normal: ${overrides.cem_clipped_normal}
min_component_weight: 0.01
